### ISSUE TITLE
ERROR EN samples/monthcalendar/month.prg

### ISSUE THREAD

**Issue by jimeneztatodavid** [oohg/samples#14]
Hola, no se si estoy haciendo algo mal, pero en el ejemplo month.prg por mucho que cambie el tamaño de la fuente el calendario no cambia ni la fuente, ni el tamaño del calendario.

**Comment by fyurisich** [comment]
Windows no permite modificar la fuente si el control tiene habilitado el "estilo visual" o sea si usa los temas de Windows.
Para poder cambiar la fuente debes deshabilitar los temas y luego hacer el cambio.
Modifiqué el ejemplo para mostrar como se hace.
Mira [https://github.com/oohg/samples/blob/master/monthcalendar/s001.prg](https://github.com/oohg/samples/blob/master/monthcalendar/s001.prg)
